name = "erdos993_eventual"
version = "0.1.0"
defaultTargets = ["Erdos993"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false
pp.unicode.fun = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "8a178386ffc0f5fef0b77738bb5449d50efeea95"

[[lean_lib]]
name = "Erdos993"
